apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-engine-demo
  labels:
    app: db-engine-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-engine-demo
  template:
    metadata:
      labels:
        app: db-engine-demo
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "db-engine-demo"
        vault.hashicorp.com/agent-inject-secret-db-env: "database/creds/readonly"
        #vault.hashicorp.com/agent-inject-restart-trigger: "true"
        vault.hashicorp.com/agent-inject-template-db-env: |
          {{- with secret "database/creds/readonly" -}}
          export DB_USERNAME={{ .Data.username }}
          export DB_PASSWORD={{ .Data.password }}
          export DB_HOST="postgres-demo.default.svc.cluster.local"
          export DB_NAME=demo
          {{- end }}
        vault.hashicorp.com/agent-inject-file-db-env: "db.env"
    spec:
      serviceAccountName: db-engine-demo-sa  # Must be bound to the Vault role
      containers:
        - name: app
          image: c1sv3r/db-engine-demo:3.0
          env:
            - name: DB_CREDENTIALS_FILE
              value: "/vault/secrets/db.env"
          ports:
            - containerPort: 8080

