# Change
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-kms
  namespace: vault
  annotations:
    eks.amazonaws.com/role-arn: ${VAULT_ROLE_ARN}
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-kms-role
  namespace: vault
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-kms-rolebinding
  namespace: vault
subjects:
  - kind: ServiceAccount
    name: vault-kms
    namespace: vault
roleRef:
  kind: Role
  name: vault-kms-role
  apiGroup: rbac.authorization.k8s.io