apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-agent-injector
  namespace: vault
spec:
  interval: 5m
  chart:
    spec:
      chart: vault
      version: "0.30.0"
      sourceRef:
        kind: HelmRepository
        name: hashicorp-helm
        namespace: app
  values:
    global:
      enabled: false
      externalVaultAddress: "http://vault.tooling.internal:8200"
    injector:
      enabled: true
      externalVaultAddr: "http://vault.tooling.internal:8200"
