apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: external-secrets-git
  namespace: repos
spec:
  interval: 10m
  ref:
    branch: main
  url: http://github.com/external-secrets/external-secrets