apiVersion: v1
kind: Service
metadata:
  name: vault-nlb-internal
  namespace: vault
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
spec:
  type: LoadBalancer
  ports:
    - port: 8200
      targetPort: 8200
      protocol: TCP
  selector:
    app.kubernetes.io/name: vault