apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/excludeOutboundPorts: "8200"
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "catalog-role"
        vault.hashicorp.com/auth-path: "auth/app-cluster"
        vault.hashicorp.com/reload-on-secret-change: "true"
        vault.hashicorp.com/agent-inject-template-db-creds.json: |
          {{- with secret "database/creds/catalog-role" }}
          {
            "username": "{{ .Data.username }}",
            "password": "{{ .Data.password }}"
          }
          {{- end }}
      labels:
        app: catalog
    spec:
      serviceAccountName: catalog-sa
      containers:
        - name: catalog
          image: c1sv3r/app-catalog:latest
          ports:
            - containerPort: 8080
          securityContext:
            capabilities:
              drop:
                - ALL

---
apiVersion: v1
kind: Service
metadata:
  name: catalog
  namespace: app
spec:
  selector:
    app: catalog
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080