apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager
  namespace: eso
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: eso-irsa-sa
            namespace: eso
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-helm-values
  namespace: vault
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: vault-helm-values
    template:
      type: Opaque
      data:
        values.yaml: |
          server:
            serviceAccount:
              create: false
              name: vault-kms
            persistence:
              enabled: true
              storageClass: "efs-sc"
              size: "10Gi"
            ha:
              enabled: true
              raft:
                enabled: true
                setNodeId: true
                config: |
                  cluster_name = "vault-integrated-storage"

                  storage "raft" {
                    path = "/vault/data"
                    retry_join {
                      leader_api_addr = "http://vault-0.vault-internal:8200"
                    }
                  }

                  listener "tcp" {
                    address = "[::]:8200"
                    cluster_address = "[::]:8201"
                    tls_disable = "true"
                  }

                  service_registration "kubernetes" {}

                  seal "awskms" {
                    region = "eu-west-1"
                    kms_key_id = "{{ .kms_key_id }}"
                  }
          ui:
            enabled: true
          injector:
            enabled: false
  dataFrom:
    - extract:
        key: kms/kms_key_id_cis