apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: gitlab
  name: runner-secrets-rolebinding
subjects:
- kind: ServiceAccount
  name: gitlab-runner
  namespace: gitlab
roleRef:
  kind: Role
  name: runner-secrets-role
  apiGroup: rbac.authorization.k8s.io

