    namespace: vault
    image: c1sv3r/vault-bootstrap:2.0
    vaultAddr: http://vault.vault.svc.cluster.local:8200

    db:
      username: root
      password: rootpassword
      name: mysql-db
      role: readonly-role
      secret: vault-mysql-creds
      host: mysql.default.svc.cluster.local
      port: "3306"
      engineName: mysql
      plugin: mysql-database-plugin
      connectionUrl: "{{username}}:{{password}}@tcp(mysql.default.svc.cluster.local:3306)/"
      creationStatements: CREATE USER \{{name}}\@'%' IDENTIFIED BY '{{password}}'; GRANT SELECT ON *.* TO \{{name}}\@'%';
      defaultTtl: 1h
      maxTtl: 24h