apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      version: "v1"
      path: "kv"
      auth:
        kubernetes:
          mountPath: "tooling-cluster"
          role: "eso-role"
          serviceAccountRef:
            name: vault-backend
            namespace: eso
