apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-db-mariadb
  namespace: vault
spec:
  interval: 5m
  chart:
    spec:
      chart: ./tooling/vault/config/database-engine
      sourceRef:
        kind: GitRepository
        name: vault-config-repo
        namespace: flux-system
  values:
    namespace: vault
    image: c1sv3r/vault-bootstrap:2.0
    vaultAddr: http://vault.vault.svc.cluster.local:8200

    db:
      username: root
      password: rootpassword
      name: mariadb-db
      role: readonly-role
      secret: vault-mariadb-creds
      host: mariadb.default.svc.cluster.local
      port: "3306"
      engineName: mariadb
      plugin: mysql-legacy-database-plugin
      connectionUrl: "{{username}}:{{password}}@tcp(mariadb.default.svc.cluster.local:3306)/"
      creationStatements: >-
        CREATE USER `{{name}}`@'%' IDENTIFIED BY '{{password}}';
        GRANT SELECT ON *.* TO `{{name}}`@'%';
      defaultTtl: 1h
      maxTtl: 24h
