apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-db-mongo
  namespace: vault
spec:
  interval: 5m
  chart:
    spec:
      chart: ./tooling/vault/config/database-engine
      sourceRef:
        kind: GitRepository
        name: vault-config-repo
        namespace: flux-system
  values:
    namespace: vault
    image: c1sv3r/vault-bootstrap:2.0
    vaultAddr: http://vault.vault.svc.cluster.local:8200

    db:
      username: vaultuser
      password: vaultpassword
      name: mongo-db
      role: readonly-role
      secret: vault-mongo-creds
      host: mongo.default.svc.cluster.local
      port: "27017"
      engineName: mongodb
      plugin: mongodb-database-plugin
      connectionUrl: "mongodb://{{username}}:{{password}}@mongo.default.svc.cluster.local:27017/admin?authSource=admin"
      creationStatements: >-
        {
          "db": "admin",
          "roles": [
            {
              "role": "read",
              "db": "your_database"
            }
          ]
        }
      defaultTtl: 1h
      maxTtl: 24h
