apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-db-mssql
  namespace: vault
spec:
  interval: 5m
  chart:
    spec:
      chart: ./tooling/vault/config/database-engine
      sourceRef:
        kind: GitRepository
        name: vault-config-repo
        namespace: flux-system
  values:
    namespace: vault
    image: c1sv3r/vault-bootstrap:2.0
    vaultAddr: http://vault.vault.svc.cluster.local:8200

    db:
      username: sa
      password: yourStrong(!)Password
      name: mssql-db
      role: readonly-role
      secret: vault-mssql-creds
      host: mssql.default.svc.cluster.local
      port: "1433"
      engineName: mssql
      plugin: mssql-database-plugin
      connectionUrl: "sqlserver://{{username}}:{{password}}@mssql.default.svc.cluster.local:1433"
      creationStatements: >-
        CREATE LOGIN [{{name}}] WITH PASSWORD = '{{password}}';
        CREATE USER [{{name}}] FOR LOGIN [{{name}}];
        ALTER ROLE db_datareader ADD MEMBER [{{name}}];
      defaultTtl: 1h
      maxTtl: 24h
