apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-db-postgres
  namespace: vault
spec:
  interval: 5m
  chart:
    spec:
      chart: ./tooling/vault/config/database-engine
      sourceRef:
        kind: GitRepository
        name: vault-config-repo
        namespace: flux-system
  values:
    namespace: vault
    image: c1sv3r/vault-bootstrap:2.0
    vaultAddr: http://vault.vault.svc.cluster.local:8200

    db:
      username: vaultuser
      password: vaultpassword
      name: postgres-db
      role: readonly-role
      secret: vault-postgres-creds
      host: postgres.default.svc.cluster.local
      port: "5432"
      engineName: postgres
      plugin: postgresql-database-plugin
      connectionUrl: "postgresql://{{username}}:{{password}}@postgres.default.svc.cluster.local:5432/postgres?sslmode=disable"
      creationStatements: >-
        CREATE ROLE "{{name}}" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}';
        GRANT CONNECT ON DATABASE postgres TO "{{name}}";
        GRANT USAGE ON SCHEMA public TO "{{name}}";
        GRANT SELECT ON ALL TABLES IN SCHEMA public TO "{{name}}";
      defaultTtl: 1h
      maxTtl: 24h
