apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: namespaces-repo
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: <>
  ignore: |
    /*
    !/tooling/namespaces/**
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: namespaces
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./tooling/namespaces/
  prune: true
  sourceRef:
    kind: GitRepository
    name: namespaces-repo
  wait: true
