apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio-helmrepo
  namespace: flux-system
spec:
  interval: 1m
  path: ./app/repos/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: istio-system
  wait: true
