apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio-policies
  namespace: flux-system
spec:
  interval: 5m
  path: ./app/istio/policies
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: istio-core
    - name: istio-base
  wait: true
  timeout: 2m
