apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sa
  namespace: flux-system
spec:
  postBuild:
    substituteFrom:
      - kind: Secret
        name: bootstrap-secrets
  interval: 5m0s
  path: ./app/sa
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
    - name: namespaces