apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vault-injector
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./app/vault-injector/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
    - name: namespaces
    - name: repos