apiVersion: batch/v1
kind: Job
metadata:
  name: vault-enable-kv
  namespace: vault
spec:
  template:
    spec:
      serviceAccountName: vault-kms
      restartPolicy: Never
      containers:
        - name: enable-kv
          image: hashicorp/vault:1.14.0
          command:
            - /bin/sh
            - -c
            - |
              export VAULT_ADDR=http://vault.vault.svc.cluster.local:8200
              export VAULT_TOKEN=$(cat /vault/root_token)

              vault secrets enable -path=secret kv-v2 || echo "KV already enabled"
          volumeMounts:
            - name: vault-storage
              mountPath: /vault
      volumes:
        - name: vault-storage
          emptyDir: {}
