apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: ui-latest
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: ui-repo
  policy:
    semver:
      range: "*"
